### ISSUE TITLE
Discord link expired

### ISSUE THREAD

**Issue by simondorfman** [DVStakers/docs#2]
The discord link at the bottom of the home page and FAQ page must have expired. Here's the message I get when I try to join:
<img width="431" alt="Screenshot 2024-06-18 at 2 45 39 PM" src="https://github.com/DVStakers/docs/assets/106923/1f8986dd-596a-4b73-81dd-68651c7fc445">

**Comment by EridianAlpha** [comment]
Thanks @simondorfman for letting us know, I've just updated the invite link 👍
